sudo: false

language: erlang

otp_release:
 - 19.1
 - 19.2
 - 19.3

install: "true"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - ./rebar3 compile
  - ./rebar3 xref

jobs:
  include:
    - stage: ci-test
      otp_release: 19.3
      script:
        - ./rebar3 as integration ct --dir test/integration
