sudo: false

dist: xenial

language: erlang

otp_release:
 - 20.0
 - 20.1

install: "true"

script:
  - rebar3 compile
  - rebar3 xref
  - rebar3 do xref, ct, coveralls send

notifications:
  slack:
    secure: "RfqEC4hI9OnCyx3hAx0vN4vhb8ERFmwt6mT1qj3X/PMtcw0tkA6e5b3I5Ioeeq54SIyPZCtSHa4GrAJrPuM7sSJaSbpTPHOdeCsDOt5R1d7BM3yeHmgCS/0g5RsMAAm+YbA1pKGntt/8/6uppxrgfmRGYU/FXfzJ5XdJxSrLzh4SGH8fSpovxIgU5xA0jKjbZHWeQpQp1kgLXJh3jHxAuPXzsXQlRNAj1m4/82AB1WK4wmG0DEGWVKbZTmeIfNuIkXOcTd6iNTyeGwEj0cA/kDfiJO93fZ8Zrp+wtrYyjn/oqcHwiKINzvpcMs4K/0x5wv2+1+VJUhfsHXQSz2LwnPMYH8XqTr4b6BYwUOpTubZM/a4vKAqhHmOpX28IFucCx9s2jtDFS4E5IV8HOsgbb5bL6jKK96Gdf77H8AaZQ0EZZgJ/1nCuSHLglglb0H/ME8qsQQS3DvY/6lnCOtcW1Y0RPtoHF2bF4O0IiRSoq/1UdO5Ta/F4d4Y28g7UoeXVP38JnXgqzW6ElmCQ0n1r3w5zNssw9Y18UF3tnT696ioQ6YzAXWrLOj0V2VWhSrJ+FBS38W3P7jGFg9V5OQjGfBcN84mxvjGpWhIeAdOdfJcpGkCz5ri2lrEkTkAIB4NgizpWlZujfTPWh1Io+iT7sx0b6aT1emRaHAIPRMnW2no="
